name: 'Seek Deployment'
description: 'Seek Deployment for a specific `ref`, `environment` and `status`'
author: james-leha@github.com, hello@cloudposse.com
branding:
  icon: 'server'
  color: 'white'
inputs:
  github-token: 
    description: The GitHub token
    default: ${{ github.token }}
    required: true
  owner:
    description: 'Repository Owner (defaults to current)'
    required: false  
  repo:
    description: 'Repository (defaults to current)'
    required: false
  ref:
    description: 'Branch or commit SHA'
    required: true
  environment:
    description: 'Environment name'
    required: true
  status:
    description: 'Deployment status'
    required: false  
outputs:
  id: 
    description: 'Deployment ID'
runs:
  using: 'node12'
  main: 'index.js'
